DIG_CORE_DIR_WIN=$(PROJECT_PATH_WIN)/Digital_core/src

digital_core_rtl: gpp_rtl
	$(COMP) $(COMP_RTL_FLAGS) $(DIG_CORE_DIR_WIN)/digital_core.vhd

include $(PROJECT_PATH)/Processors/IM3000E/src/Makefile
