FPGA_NOC_ADAPTER_TB_DIR=$(PROJECT_PATH)/Digital_core/tb/fpga_noc_adapter_tb
FPGA_NOC_ADAPTER_TB_DIR_WIN=$(PROJECT_PATH_WIN)/Digital_core/tb/fpga_noc_adapter_tb

fpga_noc_adapter_tb :
	$(COMP) $(COMP_TB_FLAGS) $(FPGA_NOC_ADAPTER_TB_DIR_WIN)/fpga_noc_adapter_tb.vhd
