//---------------------------------------------------------------------
//               Copyright(c) Synopsys, Inc.                           
//     All Rights reserved - Unpublished -rights reserved under        
//     the Copyright laws of the United States of America.             
//                                                                     
//  U.S. Patents: 7,093,156 B1 and 7,406,620 B2 (and more pending).    
//                                                                     
//  This file includes the Confidential information of Synopsys, Inc.  
//  and GLOBALFOUNDRIES.                                               
//  The receiver of this Confidential Information shall not disclose   
//  it to any third party and shall protect its confidentiality by     
//  using the same degree of care, but not less than a reasonable      
//  degree of care, as the receiver uses to protect receiver's own     
//  Confidential Information.                                          
//  Licensee acknowledges and agrees that all output generated for     
//  Licensee by Synopsys, Inc. as described in the pertinent Program   
//  Schedule(s), or generated by Licensee through use of any Compiler  
//  licensed hereunder contains information that complies with the     
//  Virtual Component Identification Physical Tagging Standard (VCID)  
//  as maintained by the Virtual Socket Interface Alliance (VSIA).     
//  Such information may be expressed in GDSII Layer 63 or other such  
//  layer designated by the VSIA, hardware definition languages, or    
//  other formats.  Licensee is not authorized to alter or change any  
//  such information.                                                  
//---------------------------------------------------------------------
//                                                                     
//  Built for linux64 and running on linux64.                          
//                                                                     
//  Software           : Rev: S-2021.09-SP1                            
//  Library Format     : Rev: 1.05.00                                  
//  Compiler Name      : gf22nsd41p11s1srl256sa04p1                    
//  Platform           : Linux3.10.0-957.5.1.el7.x86_64                
//                     : #1 SMP Wed Dec 19 10:46:58 EST 2018x86_64     
//  Date of Generation : Mon May 23 13:52:35 CEST 2022                 
//                                                                     
//---------------------------------------------------------------------
//   --------------------------------------------------------------     
//                       Template Revision : 6.3.7                      
//   --------------------------------------------------------------     
//                 * Synchronous, 1-Port Register File *              
//                         * Verilog Stub Model *                     
//                THIS IS A SYNCHRONOUS 1-PORT MEMORY MODEL           
//                                                                    
//   Memory Name:SNPS_RF_SP_UHS_1024x8                                
//   Memory Size:1024 words x 8 bits                                  
//                                                                    
//                               PORT NAME                            
//                               ---------                            
//               Output Ports                                         
//                                   Q[7:0]                           
//               Input Ports:                                         
//                                   ADR[9:0]                         
//                                   D[7:0]                           
//                                   WE                               
//                                   ME                               
//                                   CLK                              
//                                   TEST1                            
//                                   TEST_RNM                         
//                                   RME                              
//                                   RM[3:0]                          
//                                   WA[1:0]                          
//                                   WPULSE[2:0]                      
//                                   LS                               
//                                   BC0                              
//                                   BC1                              
//                                   BC2                              
// -------------------------------------------------------------------- 


`resetall 

`timescale 1 ns / 1 ps 
`celldefine 

module SNPS_RF_SP_UHS_1024x8 ( Q, ADR, D, WE, ME, CLK, TEST1, TEST_RNM, RME, RM, WA, WPULSE, LS, BC0, BC1, BC2);

parameter bits = 8, addrbits = 10;

// -----------------------------------------------------------------------------
// Module Pins Definition
// -----------------------------------------------------------------------------
// Outputs

output [bits-1:0] Q;

// Inputs

input [addrbits-1:0] ADR;
input [bits-1:0] D;
input WE;
input ME;
input CLK;
input TEST1;
input TEST_RNM;
input RME;
input  [3:0] RM;
input  [1:0] WA;
input  [2:0] WPULSE;
input LS;
input BC0;
input BC1;
input BC2;


// -----------------------------------------------------------------------------
// Output assignments for stub mode
// -----------------------------------------------------------------------------

assign Q = 8'b0;

endmodule
`endcelldefine 
