
# create_generated_clock -name ld_bmem -divide_by 2 [get_pins {core1/crb/ld_bmem_reg/Q}] -source [get_ports HCLK]

set_property PACKAGE_PIN AY9 [get_ports {OSPI_Out[CK_p]}]
set_property PACKAGE_PIN BA9 [get_ports {OSPI_Out[CK_n]}]
set_property PACKAGE_PIN BE12 [get_ports {OSPI_Out[CS_n]}]
set_property PACKAGE_PIN BF10 [get_ports {OSPI_Out[RESET_n]}]
set_property PACKAGE_PIN BD12 [get_ports OSPI_RWDS]
set_property PACKAGE_PIN BD13 [get_ports {OSPI_DQ[0]}]
set_property PACKAGE_PIN BE13 [get_ports {OSPI_DQ[1]}]
set_property PACKAGE_PIN BB13 [get_ports {OSPI_DQ[2]}]
set_property PACKAGE_PIN BB12 [get_ports {OSPI_DQ[3]}]
set_property PACKAGE_PIN BE14 [get_ports {OSPI_DQ[4]}]
set_property PACKAGE_PIN BF14 [get_ports {OSPI_DQ[5]}]
set_property PACKAGE_PIN BA14 [get_ports {OSPI_DQ[6]}]
set_property PACKAGE_PIN BB14 [get_ports {OSPI_DQ[7]}]
set_property PACKAGE_PIN BE15 [get_ports MCKOUT0]
set_property PACKAGE_PIN BF9 [get_ports MRESET]
set_property PACKAGE_PIN BF15 [get_ports MSDIN]
set_property PACKAGE_PIN BC14 [get_ports MSDOUT]
set_property PACKAGE_PIN BC15 [get_ports MIRQ0]
set_property PACKAGE_PIN BC13 [get_ports MIRQOUT]
set_property PACKAGE_PIN BA37 [get_ports {LED[7]}]
set_property PACKAGE_PIN AV36 [get_ports {LED[6]}]
set_property PACKAGE_PIN AU37 [get_ports {LED[5]}]
set_property PACKAGE_PIN BF32 [get_ports {LED[4]}]
set_property PACKAGE_PIN BB32 [get_ports {LED[3]}]
set_property PACKAGE_PIN AY30 [get_ports {LED[2]}]
set_property PACKAGE_PIN AV34 [get_ports {LED[1]}]
set_property PACKAGE_PIN AT32 [get_ports {LED[0]}]

set_property PACKAGE_PIN BB16 [get_ports OE_CTR]
set_property PACKAGE_PIN AP13 [get_ports PA6_SCK]
set_property PACKAGE_PIN AR13 [get_ports PA5_CS_N]
set_property PACKAGE_PIN AV10 [get_ports PA0_SIN]
set_property PACKAGE_PIN AW10 [get_ports PA7_SOUT]
set_property PACKAGE_PIN AK13 [get_ports ENET_TXD3]
set_property PACKAGE_PIN AK14 [get_ports ENET_TXD2]
set_property PACKAGE_PIN AM12 [get_ports ENET_TXD1]
set_property PACKAGE_PIN AM13 [get_ports ENET_TXD0]
set_property PACKAGE_PIN AV13 [get_ports ENET_TXCTL]
set_property PACKAGE_PIN AV14 [get_ports ENET_TXCLK]
set_property PACKAGE_PIN AJ12 [get_ports ENET_RXD3]
set_property PACKAGE_PIN AJ13 [get_ports ENET_RXD2]
set_property PACKAGE_PIN AL12 [get_ports ENET_RXD1]
set_property PACKAGE_PIN AK12 [get_ports ENET_RXD0]
set_property PACKAGE_PIN AT14 [get_ports ENET_RXCTL]
set_property PACKAGE_PIN AR14 [get_ports ENET_RXCLK]
set_property PACKAGE_PIN BD15 [get_ports ENET_RST_N]
set_property PACKAGE_PIN BD11 [get_ports ENET_MDIO]
set_property PACKAGE_PIN BC11 [get_ports ENET_MDC]
set_property PACKAGE_PIN AW8 [get_ports {TEST_OUTP[0]}]
set_property PACKAGE_PIN AW7 [get_ports {TEST_OUTP[1]}]
set_property PACKAGE_PIN AP12 [get_ports {TEST_OUTP[2]}]
set_property PACKAGE_PIN AR12 [get_ports {TEST_OUTP[3]}]
set_property PACKAGE_PIN AL14 [get_ports {TEST_OUTP[4]}]
set_property PACKAGE_PIN AM14 [get_ports {TEST_OUTP[5]}]
set_property PACKAGE_PIN AY8 [get_ports {TEST_OUTP[6]}]
set_property PACKAGE_PIN AY7 [get_ports {TEST_OUTP[7]}]
set_property PACKAGE_PIN AN16 [get_ports {TEST_OUTP[8]}]
set_property PACKAGE_PIN AP16 [get_ports {TEST_OUTP[9]}]
set_property PACKAGE_PIN AK15 [get_ports {TEST_OUTP[10]}]
set_property PACKAGE_PIN AL15 [get_ports {TEST_OUTP[11]}]
set_property PACKAGE_PIN AV9 [get_ports {TEST_OUTP[12]}]
set_property PACKAGE_PIN AV8 [get_ports {TEST_OUTP[13]}]
set_property PACKAGE_PIN AW11 [get_ports {TEST_OUTP[14]}]
set_property PACKAGE_PIN AY10 [get_ports {TEST_OUTP[15]}]
set_property PACKAGE_PIN BC9 [get_ports URX]
set_property PACKAGE_PIN BC8 [get_ports UTX]

set_property IOSTANDARD LVCMOS18 [get_ports {TEST_OUTP[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_OUTP[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_OUTP[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_OUTP[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_OUTP[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_OUTP[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_OUTP[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_OUTP[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_OUTP[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_OUTP[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_OUTP[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_OUTP[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_OUTP[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_OUTP[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_OUTP[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TEST_OUTP[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSPI_DQ[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSPI_DQ[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSPI_DQ[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSPI_DQ[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSPI_DQ[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSPI_DQ[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSPI_DQ[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSPI_DQ[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports MSDOUT]
set_property IOSTANDARD LVCMOS18 [get_ports OE_CTR]
set_property IOSTANDARD LVCMOS18 [get_ports {OSPI_Out[CK_n]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSPI_Out[CK_p]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSPI_Out[CS_n]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSPI_Out[RESET_n]}]
set_property IOSTANDARD LVCMOS18 [get_ports OSPI_RWDS]
set_property IOSTANDARD LVCMOS18 [get_ports PA0_SIN]
set_property IOSTANDARD LVCMOS18 [get_ports PA5_CS_N]
set_property IOSTANDARD LVCMOS18 [get_ports PA6_SCK]
set_property IOSTANDARD LVCMOS18 [get_ports PA7_SOUT]
set_property IOSTANDARD LVCMOS18 [get_ports URX]
set_property IOSTANDARD LVCMOS18 [get_ports UTX]
set_property IOSTANDARD LVCMOS18 [get_ports ENET_TXCTL]
set_property IOSTANDARD LVCMOS18 [get_ports ENET_TXD0]
set_property IOSTANDARD LVCMOS18 [get_ports ENET_TXD1]
set_property IOSTANDARD LVCMOS18 [get_ports ENET_TXD2]
set_property IOSTANDARD LVCMOS18 [get_ports ENET_TXD3]
set_property IOSTANDARD LVCMOS18 [get_ports MCKOUT0]
set_property IOSTANDARD LVCMOS18 [get_ports ENET_MDC]
set_property IOSTANDARD LVCMOS18 [get_ports ENET_MDIO]
set_property IOSTANDARD LVCMOS18 [get_ports ENET_RST_N]
set_property IOSTANDARD LVCMOS18 [get_ports MIRQOUT]
set_property IOSTANDARD LVCMOS18 [get_ports ENET_RXCLK]
set_property IOSTANDARD LVCMOS18 [get_ports ENET_RXCTL]
set_property IOSTANDARD LVCMOS18 [get_ports ENET_RXD0]
set_property IOSTANDARD LVCMOS18 [get_ports ENET_RXD1]
set_property IOSTANDARD LVCMOS18 [get_ports ENET_RXD2]
set_property IOSTANDARD LVCMOS18 [get_ports ENET_RXD3]
set_property IOSTANDARD LVCMOS18 [get_ports ENET_TXCLK]
set_property IOSTANDARD LVCMOS18 [get_ports MIRQ0]
set_property IOSTANDARD LVCMOS18 [get_ports MRESET]
set_property IOSTANDARD LVCMOS18 [get_ports MSDIN]

set_property PACKAGE_PIN AY14 [get_ports {pmod0_in[0]}]
set_property PACKAGE_PIN AY15 [get_ports {pmod0_in[1]}]
set_property PACKAGE_PIN AW15 [get_ports {pmod0_in[2]}]
set_property PACKAGE_PIN AV15 [get_ports {pmod0_out[3]}]
set_property PACKAGE_PIN AV16 [get_ports {pmod0_out[4]}]

set_property IOSTANDARD LVCMOS18 [get_ports {pmod0_in[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod0_in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod0_in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod0_out[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pmod0_out[4]}]

# No PMOD is clock capable, so override this requirement. Should be ok, the SPI clock is slow.
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {pmod0_in_IBUF[0]_inst/O}]

create_clock -period 20.000 -name ENET_TXCLK -waveform {0.000 10.000} [get_ports ENET_TXCLK]
set_clock_groups -name ENET_TXCLK -asynchronous -group [get_clocks ENET_TXCLK]

create_clock -period 20.000 -name ENET_RXCLK -waveform {0.000 10.000} [get_ports ENET_RXCLK]
set_clock_groups -name ENET_RXCLK -asynchronous -group [get_clocks ENET_RXCLK]

create_clock -period 100.000 -name SPI_SCK -waveform {0.000 50.000} [get_ports {pmod0_in[0]}]
set_clock_groups -name SPI_CLK -asynchronous -group [get_clocks SPI_SCK]


set_input_delay -clock [get_clocks ENET_RXCLK] -min -add_delay 3.000 [get_ports ENET_RXCTL]
set_input_delay -clock [get_clocks ENET_RXCLK] -min -add_delay 3.000 [get_ports ENET_RXD0]
set_input_delay -clock [get_clocks ENET_RXCLK] -min -add_delay 3.000 [get_ports ENET_RXD1]
set_input_delay -clock [get_clocks ENET_RXCLK] -min -add_delay 3.000 [get_ports ENET_RXD3]

set_input_delay -clock [get_clocks ENET_RXCLK] -max -add_delay 5.000 [get_ports ENET_RXCTL]
set_input_delay -clock [get_clocks ENET_RXCLK] -max -add_delay 5.000 [get_ports ENET_RXD0]
set_input_delay -clock [get_clocks ENET_RXCLK] -max -add_delay 5.000 [get_ports ENET_RXD1]
set_input_delay -clock [get_clocks ENET_RXCLK] -max -add_delay 5.000 [get_ports ENET_RXD3]

set_output_delay -clock [get_clocks ENET_TXCLK] -min -add_delay -2.000 [get_ports ENET_TXCTL]
set_output_delay -clock [get_clocks ENET_TXCLK] -min -add_delay -2.000 [get_ports ENET_TXD0]
set_output_delay -clock [get_clocks ENET_TXCLK] -min -add_delay -2.000 [get_ports ENET_TXD1]
set_output_delay -clock [get_clocks ENET_TXCLK] -min -add_delay -2.000 [get_ports ENET_TXD3]

set_output_delay -clock [get_clocks ENET_TXCLK] -max -add_delay 5.000 [get_ports ENET_TXCTL]
set_output_delay -clock [get_clocks ENET_TXCLK] -max -add_delay 5.000 [get_ports ENET_TXD0]
set_output_delay -clock [get_clocks ENET_TXCLK] -max -add_delay 5.000 [get_ports ENET_TXD1]
set_output_delay -clock [get_clocks ENET_TXCLK] -max -add_delay 5.000 [get_ports ENET_TXD3]

# CS
#set_input_delay -clock [get_clocks SPI_SCK] -min -add_delay 48.000 [get_ports {pmod0_in[1]}]
#set_input_delay -clock [get_clocks SPI_SCK] -max -add_delay 52.000 [get_ports {pmod0_in[1]}]

# MOSI
#set_input_delay -clock [get_clocks SPI_SCK] -min -add_delay 48.000 [get_ports {pmod0_in[2]}]
#set_input_delay -clock [get_clocks SPI_SCK] -max -add_delay 52.000 [get_ports {pmod0_in[2]}]




#set_output_delay -clock [get_clocks SPI_SCK] 1.000 [get_ports {pmod0_out[*]}]

# set_input_delay -clock [get_clocks -of_objects [get_pins fpga_pll_inst/inst/mmcme4_adv_inst/CLKOUT1]] -min -add_delay 1.000 [get_ports {OSPI_DQ[*]}]
#set_input_delay -clock [get_clocks -of_objects [get_pins fpga_pll_inst/inst/mmcme4_adv_inst/CLKOUT1]] -min -add_delay 1.000 [get_ports OSPI_RWDS]
set_input_delay -clock [get_clocks clk_100M_clk_wiz_0] -max 2.000 [get_ports {OSPI_DQ[*]}]
set_input_delay -clock [get_clocks clk_100M_clk_wiz_0] -max 2.000 [get_ports OSPI_RWDS]


set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] 1.000 [get_ports {OSPI_DQ[*]}]
set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] 1.000 [get_ports OSPI_RWDS]
set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] 1.000 [get_ports {OSPI_Out[*]}]
#set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -min -add_delay -1.000 [get_ports {OSPI_DQ[*]}]
#set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -min -add_delay -1.000 [get_ports OSPI_RWDS]
#set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -min -add_delay -1.000 [get_ports {OSPI_Out[*]}]
#set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -max -add_delay -0.250 [get_ports {OSPI_DQ[*]}]
#set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -max -add_delay -0.250 [get_ports OSPI_RWDS]
#set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -max -add_delay -0.250 [get_ports {OSPI_Out[*]}]


set_input_delay -clock [get_clocks clk_100M_clk_wiz_0] -min -add_delay 2.000 [get_ports ENET_MDIO]
set_input_delay -clock [get_clocks clk_100M_clk_wiz_0] -max -add_delay 5.000 [get_ports ENET_MDIO]

set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -min -add_delay -1.000 [get_ports ENET_MDIO]
set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -max -add_delay -0.100 [get_ports ENET_MDIO]

set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -min -add_delay -1.000 [get_ports ENET_MDC]
set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -max -add_delay -0.100 [get_ports ENET_MDC]

#set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -min -add_delay -1.000 [get_ports ENET_RST_N]
#set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -max -add_delay 0.500 [get_ports ENET_RST_N]

set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -min -add_delay -1.000 [get_ports PA0_SIN]
set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -max -add_delay 0.100 [get_ports PA0_SIN]
set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -min -add_delay -1.000 [get_ports PA5_CS_N]
set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -max -add_delay 0.100 [get_ports PA5_CS_N]
set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -min -add_delay -1.000 [get_ports PA6_SCK]
set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -max -add_delay 0.100 [get_ports PA6_SCK]
set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -min -add_delay -1.000 [get_ports PA7_SOUT]
set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -max -add_delay 0.100 [get_ports PA7_SOUT]
set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -min -add_delay -1.000 [get_ports URX]
set_output_delay -clock [get_clocks clk_100M_clk_wiz_0] -max -add_delay 0.100 [get_ports URX]

# SPI CS to OE
set_false_path -from [get_ports {pmod0_in[1]}] -to [get_ports {pmod0_out[4]}]


# Ports
set_false_path -to [get_ports *LED*]

set_false_path -from [get_ports URX]
set_false_path -from [get_ports UTX]
set_false_path -from [get_ports MRESET]
set_false_path -from [get_ports MIRQ0]
set_false_path -from [get_ports MSDIN]

set_false_path -to [get_ports URX]
set_false_path -to [get_ports UTX]
set_false_path -to [get_ports MCKOUT0]
set_false_path -to [get_ports MSDOUT]
set_false_path -to [get_ports MIRQOUT]

set_false_path -to [get_ports ENET_RST_N]



create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list fpga_pll_inst/inst/clk_100M]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {OSPI_DQ_i[0]} {OSPI_DQ_i[1]} {OSPI_DQ_i[2]} {OSPI_DQ_i[3]} {OSPI_DQ_i[4]} {OSPI_DQ_i[5]} {OSPI_DQ_i[6]} {OSPI_DQ_i[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {digital_top_inst/i_digital_core/i_im4000_top/core1/ybus[0]} {digital_top_inst/i_digital_core/i_im4000_top/core1/ybus[1]} {digital_top_inst/i_digital_core/i_im4000_top/core1/ybus[2]} {digital_top_inst/i_digital_core/i_im4000_top/core1/ybus[3]} {digital_top_inst/i_digital_core/i_im4000_top/core1/ybus[4]} {digital_top_inst/i_digital_core/i_im4000_top/core1/ybus[5]} {digital_top_inst/i_digital_core/i_im4000_top/core1/ybus[6]} {digital_top_inst/i_digital_core/i_im4000_top/core1/ybus[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {digital_top_inst/i_digital_core/i_im4000_top/core1/dbus_int[0]} {digital_top_inst/i_digital_core/i_im4000_top/core1/dbus_int[1]} {digital_top_inst/i_digital_core/i_im4000_top/core1/dbus_int[2]} {digital_top_inst/i_digital_core/i_im4000_top/core1/dbus_int[3]} {digital_top_inst/i_digital_core/i_im4000_top/core1/dbus_int[4]} {digital_top_inst/i_digital_core/i_im4000_top/core1/dbus_int[5]} {digital_top_inst/i_digital_core/i_im4000_top/core1/dbus_int[6]} {digital_top_inst/i_digital_core/i_im4000_top/core1/dbus_int[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 80 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[0]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[1]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[2]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[3]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[4]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[5]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[6]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[7]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[8]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[9]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[10]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[11]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[12]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[13]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[14]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[15]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[16]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[17]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[18]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[19]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[20]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[21]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[22]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[23]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[24]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[25]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[26]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[27]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[28]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[29]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[30]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[31]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[32]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[33]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[34]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[35]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[36]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[37]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[38]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[39]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[40]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[41]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[42]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[43]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[44]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[45]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[46]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[47]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[48]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[49]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[50]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[51]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[52]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[53]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[54]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[55]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[56]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[57]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[58]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[59]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[60]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[61]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[62]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[63]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[64]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[65]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[66]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[67]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[68]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[69]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[70]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[71]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[72]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[73]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[74]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[75]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[76]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[77]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[78]} {digital_top_inst/i_digital_core/i_im4000_top/core1/pl[79]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list digital_top_inst/i_digital_core/i_im4000_top/core2/alu/flag_yan]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list digital_top_inst/i_digital_core/i_im4000_top/core1/alu/flag_yan]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list digital_top_inst/i_digital_core/i_im4000_top/core2/alu/flag_yz]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list digital_top_inst/i_digital_core/i_im4000_top/core1/alu/flag_yz]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list OSPI_DQ_e]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list OSPI_RWDS_e]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list OSPI_RWDS_i]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_100m]
