PEC_TB_DIR=$(PROJECT_PATH)/Accelerator/Emulator_version_demo/src/PEC/testbench
PEC_TB_DIR_WIN=$(PROJECT_PATH_WIN)/Accelerator/Emulator_version_demo/src/PEC/testbench

cluster_tb: 
	$(COMP) $(COMP_TB_FLAGS) $(PEC_TB_DIR_WIN)/c_tb.vhd \
			 	  $(PEC_TB_DIR_WIN)/Cluster_tb.vhd 
			 	 




