MEM_DIR=$(PROJECT_PATH)/IP/Synopsys/Embed-it_Integrator\compout\views
MEM_DIR_WIN=$(PROJECT_PATH_WIN)/IP/Synopsys/Embed-it_Integrator\compout\views


mem_comp:
	$(V_COMP) $(MEM_DIR_WIN)/SNPS_SP_HD_2Kx80/SNPS_SP_HD_2Kx80_fast_func.v \
		  $(MEM_DIR_WIN)/SNPS_SP_HD_16Kx8/SNPS_SP_HD_16Kx8_fast_func.v \
		  $(MEM_DIR_WIN)/SNPS_SP_HD_1024x8/SNPS_SP_HD_1024x8_fast_func.v \
		  $(MEM_DIR_WIN)/SNPS_SP_HD_512x8/SNPS_SP_HD_512x8_fast_func.v \
		  $(MEM_DIR_WIN)/SNPS_SP_HD_256x32/SNPS_SP_HD_256x32_fast_func.v
