MEM_DIR=$(PROJECT_PATH)/IP/Synopsys/Embed-it_Integrator/compout/views
MEM_DIR_WIN=$(PROJECT_PATH_WIN)/IP/Synopsys/Embed-it_Integrator/compout/views


mem_comp:
	$(V_COMP) $(MEM_DIR_WIN)/SNPS_SP_HD_2Kx80/SNPS_SP_HD_2Kx80_fast_func.v \
		  $(MEM_DIR_WIN)/SNPS_SP_HD_8Kx128/SNPS_SP_HD_8Kx128_fast_func.v \
		  $(MEM_DIR_WIN)/SNPS_SP_HD_16Kx8/SNPS_SP_HD_16Kx8_fast_func.v \
		  $(MEM_DIR_WIN)/SNPS_SP_HD_256x32/SNPS_SP_HD_256x32_fast_func.v \
		  $(MEM_DIR_WIN)/SNPS_SP_HD_512x8/SNPS_SP_HD_512x8_fast_func.v \
		  $(MEM_DIR_WIN)/SNPS_SP_HD_1024x8/SNPS_SP_HD_1024x8_fast_func.v \
		  $(MEM_DIR_WIN)/SNPS_RF_SP_UHS_64x64/SNPS_RF_SP_UHS_64x64_fast_func.v \
		  $(MEM_DIR_WIN)/SNPS_RF_SP_UHS_256x32/SNPS_RF_SP_UHS_256x32_fast_func.v \
		  $(MEM_DIR_WIN)/SNPS_RF_SP_UHS_256x64/SNPS_RF_SP_UHS_256x64_fast_func.v \
		  $(MEM_DIR_WIN)/SNPS_RF_SP_UHS_512x28/SNPS_RF_SP_UHS_512x28_fast_func.v \
		  $(MEM_DIR_WIN)/SNPS_RF_SP_UHS_1024x8/SNPS_RF_SP_UHS_1024x8_fast_func.v \
		  $(MEM_DIR_WIN)/SNPS_RF_SP_UHS_1024x32/SNPS_RF_SP_UHS_1024x32_fast_func.v \
		  $(MEM_DIR_WIN)/SNPS_ROM_4Kx80_mprom00/SNPS_ROM_4Kx80_mprom00_fast_func.v \
		  $(MEM_DIR_WIN)/SNPS_ROM_4Kx80_mprom11/SNPS_ROM_4Kx80_mprom11_fast_func.v
