TIU_BLOCK_TB_DIR=$(PROJECT_PATH)/Processors/IM3000E/tb/tiu_block_tb
TIU_BLOCK_TB_DIR_WIN=$(PROJECT_PATH_WIN)/Processors/IM3000E/tb/tiu_block_tb

tiu_block_tb : 
	$(COMP) $(COMP_TB_FLAGS) $(TIU_BLOCK_TB_DIR_WIN)/tiu_tb.vhd